backend:
  name: git-gateway
  branch: main

media_folder: "SSG/src/assets/uploads/"
public_folder: "/assets/uploads/"

collections:

  - name: "gallery" # This is the name used in the URL in the CMS (/admin/collections/gallery)
    label: "Gallery" # This is the name displayed in the CMS UI
    extension: "json" # Use JSON to manage non-Markdown data, suitable for a list of images
    editor:
      preview: false # Disable the preview if it's not necessary
    files:
      - name: "gallery" # A single file named gallery
        label: "Gallery" # Label for the gallery
        file: "_data/gallery.json" # The file to store our gallery data, Eleventy can easily access data files
        fields: # Define the fields for this gallery
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Caption", name: "caption", widget: "text", required: false}
